site_name: My Docs
#site_url: https://mydomain.org/mysite
theme:
  name: material

# mathjax: true
#markdown_extensions:
#  - pymdownx.arithmatex:
#      generic: true
#
#extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# katex: true
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - javascripts/katex.min.js
  - javascripts/auto-render.min.js

extra_css:
  - css/katex.min.css